name: Dev Deployment

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".*"      # Ignore all dotfiles
      - "*/.**"    # Ignore all dot directories and their contents

permissions:
  id-token: write        
  contents: read         

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    environment: development  
    
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Login to Azure (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev..."
          STORAGE_ACCOUNT_NAME="${{ secrets.STORAGE_ACCOUNT_NAME }}"
          CONTAINER_NAME="${{ secrets.CONTAINER_NAME }}"
          LOCAL_PATH="."

          az storage blob upload-batch \
            --account-name $STORAGE_ACCOUNT_NAME \
            --destination $CONTAINER_NAME \
            --source $LOCAL_PATH \
            --auth-mode login \
            --overwrite
