name: Preprod and Production Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_preprod:
    runs-on: ubuntu-latest
    environment: pre-production
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Pre-production
        run: |
          echo "Deploying to Pre-production..."
          STORAGE_ACCOUNT_NAME="${{ secrets.STORAGE_ACCOUNT_NAME }}"
          CONTAINER_NAME="${{ secrets.CONTAINER_NAME }}"
          LOCAL_PATH="./content"
          
          az storage blob upload-batch \
            --account-name $STORAGE_ACCOUNT_NAME \
            --destination $CONTAINER_NAME \
            --source $LOCAL_PATH \
            --auth-mode login \
            --overwrite

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_preprod
    environment: production
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Production
        run: |
          echo "Deploying to Production..."
          STORAGE_ACCOUNT_NAME="${{ secrets.STORAGE_ACCOUNT_NAME }}"
          CONTAINER_NAME="${{ secrets.CONTAINER_NAME }}"
          LOCAL_PATH="./content"
          
          az storage blob upload-batch \
            --account-name $STORAGE_ACCOUNT_NAME \
            --destination $CONTAINER_NAME \
            --source $LOCAL_PATH \
            --auth-mode login \
            --overwrite
