---
name: Generate Release PR

on:
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create App token
        id: create_token
        uses: fsdh-pfds/.github/.github/actions/create-app-token@main
        with:
          app-id: ${{ vars.FSDH_DOCS_RELEASE_APP_ID }}
          private-key: ${{ secrets.FSDH_DOCS_RELEASE_APP_KEY }}

      - name: Create Release PR
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          config-file: release-please-config.json
          token: ${{ steps.create_token.outputs.token }}
