name: Release Please

on:
  workflow_dispatch:
  push: {}


permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release PR
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          
